---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-elasticsearch
  labels:
    app: sysdigcloud
    role: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: transport-protocol
  selector:
    app: sysdigcloud
    role: elasticsearch