---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-redis
spec:
  serviceName: sysdigcloud-redis
  replicas: 2
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-secondary
        image: jequals5/redis:testing
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sysdigcloud-config
                key: redis.password
        imagePullPolicy: Always
        env:
        - name: REPLICA
          value: "true"
        ports:
        - containerPort: 6379
          name: redis-secondary
        volumeMounts:
        - name: redis-secondary-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-secondary-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
