apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-redis
  labels:
    app: sysdigcloud
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis-primary
  - port: 6379
    name: redis-secondary
  selector:
    app: redis
