---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-redis
spec:
  serviceName: sysdigcloud-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sysdigcloud-redis
        image: jequals5/redis:testing
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sysdigcloud-config
                key: redis.password
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: sysdigcloud-redis
        volumeMounts:
        - name: redis-primary-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-primary-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

